FROM python:2.7.15

COPY . /

RUN pip install -r requirements.txt

RUN useradd -ms /bin/bash nonroot

USER nonroot

RUN python manage.py makemigrations

RUN python manage.py migrate

CMD celery worker -A mm_api --app=core.celeryapp:app



