version: "3"
services:
  django_api:
    image: django_api
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
  postgres:
    image: postgres:latest
    ports:
      - "2345:5432"
    # deploy:
    #   placement:
    #     constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis:latest
    ports:
      - "9736:6379"
    # deploy:
    #   placement:
    #     constraints: [node.role == manager]
    command: redis-server
    networks:
      - webnet
networks:
  webnet: